Increase the required Firefox version
When running pencil on the linux command line, I got:

   Error: Platform version '39.0' is not compatible with 
   minVersion >= 36.0
   maxVersion <= 38.*

Instead of increasing the maxVersion to 39, it is better ti put it on 100 or so - this way we do not have to update it all the time.